Repository shanalikhan/code-settings-sync, pull requests merged in 2018-10, with the labels that each got.

#666 WIP : #258
  package.nls.ja.json
  package.nls.json
  src/service/fileService.ts
  src/setting.ts
  src/sync.ts
Labels: feature-request 💡

#670 minor grammatical fixes
  package.nls.json
Labels: improvement ✨

#676 Add webpack bundling
  .github/ISSUE_TEMPLATE/---bug-report.md
  .vscode/launch.json
  package.json
  webpack.config.js
Labels: improvement ✨

#693 Fix #686
  src/pragmaUtil.ts
  src/sync.ts
  test/pragmaUtil/index.ts
Labels: bug 🐛
