Repository shanalikhan/code-settings-sync, pull requests merged in 2019-06, with the labels that each got.

#901 Fix issues with webpack
  configs/webpack.config.js
Labels: improvement ✨

#859 [Done] Improve compatibility with different versions of VSCode
  src/enums.ts
  src/environmentPath.ts
  src/service/pluginService.ts
  src/setting.ts
  src/sync.ts
Labels: bug 🐛

#872 Fix #754 and #865
  src/pragmaUtil.ts
  src/service/github.service.ts
  src/sync.ts
  test/pragmaUtil/index.ts
  test/pragmaUtil/testSettings.txt
Labels: bug 🐛, improvement ✨

#921 Rename package.nls.pt.json to package.nls.pt-br.json
  package.nls.pt-br.json
Labels: bug 🐛

#922 Fix issues on first install
  src/commons.ts
  src/sync.ts
Labels: bug 🐛

#930 More understandable errors for @octokit/rest
  src/service/github.service.ts
  src/sync.ts
Labels: improvement ✨

#928 Fix Snippet Sync
  package.json
  src/service/file.service.ts
  src/sync.ts
Labels: bug 🐛
